const env = process.env;

const config = {
  PORT: env.PORT,
  RABBITMQ_URL: env.RABBITMQ_URL,
  DB_TYPE: env.DB_TYPE,
  MYSQL_HOST: env.MYSQL_HOST,
  MYSQL_PORT: env.MYSQL_PORT,
  MYSQL_USER: env.MYSQL_USER,
  MYSQL_PASS: env.MYSQL_PASS,
  MYSQL_NAME: env.MYSQL_NAME,
  EMAIL_ADDR: env.EMAIL_ADDR,
  EMAIL_PWD: env.EMAIL_PWD,
  SLACK_TOKEN: env.SLACK_TOKEN,
  SLACK_CONVERSATION_ID: env.SLACK_CONVERSATION_ID,
  SLACK_SIGNING_SECRET: env.SLACK_SIGNING_SECRET,
  SERVER_SECRET_KEY: env.SERVER_SECRET_KEY
};

module.exports = {
  config
};
